### PR TITLE
Update _forms.scss

### PR DESCRIPTION
**Pull request by Ismael-VC**
django-multiselectfield : from multiselectfield import MultiSelectField
display: none

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Can you put the original `issue` and `pr` links here?

**Comment by Ismael-VC** [comment]
Not everyone has made a PR nor an issue.

https://github.com/TonyMistark/django-jet/commit/e3edd1194aac10f86063cef3a2f47cc25332ad09

**Comment by SalahAdDin** [comment]
@Ismael-VC Can you review with change make it? Any problem merging this?

**Comment by Ismael-VC** [comment]
Testing....

**Pull request merged**
