### PR TITLE
Add reset button image and description.

### PR DESCRIPTION
**Pull request by Ismael-VC**
This adds an image to better find the reload button to reset widgets.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
It seems useful, thank you!

**Comment by Ismael-VC** [comment]
yeah I just didn't found the reset button at first, so I thought this would help, in a smartphone form factor this part of the gui is hidden

**Comment by SalahAdDin** [comment]
@Ismael-VC Really? Can you show us?

**Comment by Ismael-VC** [comment]
I meant hidden state is toggable:

image

image

**Comment by SalahAdDin** [comment]
Entonces no es visible en celulares?

**Comment by Ismael-VC** [comment]
Yes it is, but you ahve to click the gear icon, for the menu to show up.

**Pull request merged**
